<?php
/**
 * Array de países : Nome, Siglas e DDI
 * ID Gerado apartir de DB
 * @version 1.0
 * @since 04/02/2023
 * @author Joni Pavanello
 */
$World = array(
    4   => array('id' => 4  , 'alpha2' => 'af', 'alpha3' => 'afg', 'name' => 'Afeganistão', 'ddi' => 93),
    710 => array('id' => 710, 'alpha2' => 'za', 'alpha3' => 'zaf', 'name' => 'África do Sul', 'ddi' => 27),
    248 => array('id' => 248, 'alpha2' => 'ax', 'alpha3' => 'ala', 'name' => 'Ilhas Åland', 'ddi' => 358),
    8   => array('id' => 8  , 'alpha2' => 'al', 'alpha3' => 'alb', 'name' => 'Albânia', 'ddi' => 355),
    276 => array('id' => 276, 'alpha2' => 'de', 'alpha3' => 'deu', 'name' => 'Alemanha', 'ddi' => 49),
    20  => array('id' => 20 , 'alpha2' => 'ad', 'alpha3' => 'and', 'name' => 'Andorra', 'ddi' => 376),
    24  => array('id' => 24 , 'alpha2' => 'ao', 'alpha3' => 'ago', 'name' => 'Angola', 'ddi' => 244),
    660 => array('id' => 660, 'alpha2' => 'ai', 'alpha3' => 'aia', 'name' => 'Anguila', 'ddi' => 1),
    10  => array('id' => 10 , 'alpha2' => 'aq', 'alpha3' => 'ata', 'name' => 'Antártida', 'ddi' => 1),
    28  => array('id' => 28 , 'alpha2' => 'ag', 'alpha3' => 'atg', 'name' => 'Antígua e Barbuda', 'ddi' => 1),
    682 => array('id' => 682, 'alpha2' => 'sa', 'alpha3' => 'sau', 'name' => 'Arábia Saudita', 'ddi' => 966),
    12  => array('id' => 12 , 'alpha2' => 'dz', 'alpha3' => 'dza', 'name' => 'Argélia', 'ddi' => 213),
    32  => array('id' => 32 , 'alpha2' => 'ar', 'alpha3' => 'arg', 'name' => 'Argentina', 'ddi' => 54),
    51  => array('id' => 51 , 'alpha2' => 'am', 'alpha3' => 'arm', 'name' => 'Armênia', 'ddi' => 374),
    533 => array('id' => 533, 'alpha2' => 'aw', 'alpha3' => 'abw', 'name' => 'Aruba', 'ddi' => 297),
    36  => array('id' => 36 , 'alpha2' => 'au', 'alpha3' => 'aus', 'name' => 'Austrália', 'ddi' => 61),
    40  => array('id' => 40 , 'alpha2' => 'at', 'alpha3' => 'aut', 'name' => 'Áustria', 'ddi' => 43),
    31  => array('id' => 31 , 'alpha2' => 'az', 'alpha3' => 'aze', 'name' => 'Azerbaijão', 'ddi' => 994),
    44  => array('id' => 44 , 'alpha2' => 'bs', 'alpha3' => 'bhs', 'name' => 'Bahamas', 'ddi' => 1),
    50  => array('id' => 50 , 'alpha2' => 'bd', 'alpha3' => 'bgd', 'name' => 'Bangladexe', 'ddi' => 880),
    52  => array('id' => 52 , 'alpha2' => 'bb', 'alpha3' => 'brb', 'name' => 'Barbados', 'ddi' => 1),
    48  => array('id' => 48 , 'alpha2' => 'bh', 'alpha3' => 'bhr', 'name' => 'Barém', 'ddi' => 973),
    56  => array('id' => 56 , 'alpha2' => 'be', 'alpha3' => 'bel', 'name' => 'Bélgica', 'ddi' => 32),
    84  => array('id' => 84 , 'alpha2' => 'bz', 'alpha3' => 'blz', 'name' => 'Belize', 'ddi' => 501),
    204 => array('id' => 204, 'alpha2' => 'bj', 'alpha3' => 'ben', 'name' => 'Benim', 'ddi' => 229),
    60  => array('id' => 60 , 'alpha2' => 'bm', 'alpha3' => 'bmu', 'name' => 'Bermudas', 'ddi' => 1),
    112 => array('id' => 112, 'alpha2' => 'by', 'alpha3' => 'blr', 'name' => 'Bielorrússia', 'ddi' => 375),
    68  => array('id' => 68 , 'alpha2' => 'bo', 'alpha3' => 'bol', 'name' => 'Bolívia', 'ddi' => 591),
    535 => array('id' => 535, 'alpha2' => 'bq', 'alpha3' => 'bes', 'name' => 'Países Baixos Caribenhos', 'ddi' => 1),
    70  => array('id' => 70 , 'alpha2' => 'ba', 'alpha3' => 'bih', 'name' => 'Bósnia e Herzegovina', 'ddi' => 387),
    72  => array('id' => 72 , 'alpha2' => 'bw', 'alpha3' => 'bwa', 'name' => 'Botsuana', 'ddi' => 267),
    76  => array('id' => 76 , 'alpha2' => 'br', 'alpha3' => 'bra', 'name' => 'Brasil', 'ddi' => 55),
    96  => array('id' => 96 , 'alpha2' => 'bn', 'alpha3' => 'brn', 'name' => 'Brunei', 'ddi' => 673),
    100 => array('id' => 100, 'alpha2' => 'bg', 'alpha3' => 'bgr', 'name' => 'Bulgária', 'ddi' => 359),
    854 => array('id' => 854, 'alpha2' => 'bf', 'alpha3' => 'bfa', 'name' => 'Burquina Fasso', 'ddi' => 226),
    108 => array('id' => 108, 'alpha2' => 'bi', 'alpha3' => 'bdi', 'name' => 'Burundi', 'ddi' => 257),
    64  => array('id' => 64 , 'alpha2' => 'bt', 'alpha3' => 'btn', 'name' => 'Butão', 'ddi' => 975),
    132 => array('id' => 132, 'alpha2' => 'cv', 'alpha3' => 'cpv', 'name' => 'Cabo Verde', 'ddi' => 238),
    136 => array('id' => 136, 'alpha2' => 'ky', 'alpha3' => 'cym', 'name' => 'Ilhas Caimã', 'ddi' => 1),
    116 => array('id' => 116, 'alpha2' => 'kh', 'alpha3' => 'khm', 'name' => 'Camboja', 'ddi' => 855),
    120 => array('id' => 120, 'alpha2' => 'cm', 'alpha3' => 'cmr', 'name' => 'Camarões', 'ddi' => 237),
    124 => array('id' => 124, 'alpha2' => 'ca', 'alpha3' => 'can', 'name' => 'Canadá', 'ddi' => 1),
    634 => array('id' => 634, 'alpha2' => 'qa', 'alpha3' => 'qat', 'name' => 'Catar', 'ddi' => 974),
    398 => array('id' => 398, 'alpha2' => 'kz', 'alpha3' => 'kaz', 'name' => 'Cazaquistão', 'ddi' => 7),
    140 => array('id' => 140, 'alpha2' => 'cf', 'alpha3' => 'caf', 'name' => 'República Centro-Africana', 'ddi' => 236),
    148 => array('id' => 148, 'alpha2' => 'td', 'alpha3' => 'tcd', 'name' => 'Chade', 'ddi' => 237),
    203 => array('id' => 203, 'alpha2' => 'cz', 'alpha3' => 'cze', 'name' => 'Chéquia', 'ddi' => 420),
    152 => array('id' => 152, 'alpha2' => 'cl', 'alpha3' => 'chl', 'name' => 'Chile', 'ddi' => 56),
    156 => array('id' => 156, 'alpha2' => 'cn', 'alpha3' => 'chn', 'name' => 'China', 'ddi' => 86),
    196 => array('id' => 196, 'alpha2' => 'cy', 'alpha3' => 'cyp', 'name' => 'Chipre', 'ddi' => 357),
    166 => array('id' => 166, 'alpha2' => 'cc', 'alpha3' => 'cck', 'name' => 'Ilhas Cocos (Keeling)', 'ddi' => 672),
    170 => array('id' => 170, 'alpha2' => 'co', 'alpha3' => 'col', 'name' => 'Colômbia', 'ddi' => 57),
    174 => array('id' => 174, 'alpha2' => 'km', 'alpha3' => 'com', 'name' => 'Comores', 'ddi' => 269),
    178 => array('id' => 178, 'alpha2' => 'cg', 'alpha3' => 'cog', 'name' => 'República do Congo', 'ddi' => 242),
    180 => array('id' => 180, 'alpha2' => 'cd', 'alpha3' => 'cod', 'name' => 'República Democrática do Congo', 'ddi' => 243),
    184 => array('id' => 184, 'alpha2' => 'ck', 'alpha3' => 'cok', 'name' => 'Ilhas Cook', 'ddi' => 682),
    410 => array('id' => 410, 'alpha2' => 'kr', 'alpha3' => 'kor', 'name' => 'Coreia do Sul', 'ddi' => 82),
    408 => array('id' => 408, 'alpha2' => 'kp', 'alpha3' => 'prk', 'name' => 'Coreia do Norte', 'ddi' => 850),
    384 => array('id' => 384, 'alpha2' => 'ci', 'alpha3' => 'civ', 'name' => 'Costa do Marfim', 'ddi' => 225),
    188 => array('id' => 188, 'alpha2' => 'cr', 'alpha3' => 'cri', 'name' => 'Costa Rica', 'ddi' => 506),
    191 => array('id' => 191, 'alpha2' => 'hr', 'alpha3' => 'hrv', 'name' => 'Croácia', 'ddi' => 385),
    192 => array('id' => 192, 'alpha2' => 'cu', 'alpha3' => 'cub', 'name' => 'Cuba', 'ddi' => 53),
    531 => array('id' => 531, 'alpha2' => 'cw', 'alpha3' => 'cuw', 'name' => 'Curaçau', 'ddi' => 599),
    208 => array('id' => 208, 'alpha2' => 'dk', 'alpha3' => 'dnk', 'name' => 'Dinamarca', 'ddi' => 45),
    262 => array('id' => 262, 'alpha2' => 'dj', 'alpha3' => 'dji', 'name' => 'Djibuti', 'ddi' => 253),
    212 => array('id' => 212, 'alpha2' => 'dm', 'alpha3' => 'dma', 'name' => 'Dominica', 'ddi' => 1),
    214 => array('id' => 214, 'alpha2' => 'do', 'alpha3' => 'dom', 'name' => 'República Dominicana', 'ddi' => 1),
    818 => array('id' => 818, 'alpha2' => 'eg', 'alpha3' => 'egy', 'name' => 'Egito', 'ddi' => 20),
    222 => array('id' => 222, 'alpha2' => 'sv', 'alpha3' => 'slv', 'name' => 'El Salvador', 'ddi' => 503),
    784 => array('id' => 784, 'alpha2' => 'ae', 'alpha3' => 'are', 'name' => 'Emirados Árabes Unidos', 'ddi' => 971),
    218 => array('id' => 218, 'alpha2' => 'ec', 'alpha3' => 'ecu', 'name' => 'Equador', 'ddi' => 593),
    232 => array('id' => 232, 'alpha2' => 'er', 'alpha3' => 'eri', 'name' => 'Eritreia', 'ddi' => 291),
    703 => array('id' => 703, 'alpha2' => 'sk', 'alpha3' => 'svk', 'name' => 'Eslováquia', 'ddi' => 421),
    705 => array('id' => 705, 'alpha2' => 'si', 'alpha3' => 'svn', 'name' => 'Eslovênia', 'ddi' => 386),
    724 => array('id' => 724, 'alpha2' => 'es', 'alpha3' => 'esp', 'name' => 'Espanha', 'ddi' => 34),
    840 => array('id' => 840, 'alpha2' => 'us', 'alpha3' => 'usa', 'name' => 'Estados Unidos', 'ddi' => 1),
    233 => array('id' => 233, 'alpha2' => 'ee', 'alpha3' => 'est', 'name' => 'Estónia', 'ddi' => 372),
    748 => array('id' => 748, 'alpha2' => 'sz', 'alpha3' => 'swz', 'name' => 'Essuatíni', 'ddi' => 268),
    744 => array('id' => 744, 'alpha2' => 'sj', 'alpha3' => 'sjm', 'name' => 'Esvalbarde e Jan Mayen', 'ddi' => 0),
    231 => array('id' => 231, 'alpha2' => 'et', 'alpha3' => 'eth', 'name' => 'Etiópia', 'ddi' => 251),
    234 => array('id' => 234, 'alpha2' => 'fo', 'alpha3' => 'fro', 'name' => 'Ilhas Feroé', 'ddi' => 298),
    242 => array('id' => 242, 'alpha2' => 'fj', 'alpha3' => 'fji', 'name' => 'Fiji', 'ddi' => 679),
    608 => array('id' => 608, 'alpha2' => 'ph', 'alpha3' => 'phl', 'name' => 'Filipinas', 'ddi' => 63),
    246 => array('id' => 246, 'alpha2' => 'fi', 'alpha3' => 'fin', 'name' => 'Finlândia', 'ddi' => 358),
    250 => array('id' => 250, 'alpha2' => 'fr', 'alpha3' => 'fra', 'name' => 'França', 'ddi' => 33),
    266 => array('id' => 266, 'alpha2' => 'ga', 'alpha3' => 'gab', 'name' => 'Gabão', 'ddi' => 241),
    270 => array('id' => 270, 'alpha2' => 'gm', 'alpha3' => 'gmb', 'name' => 'Gâmbia', 'ddi' => 220),
    288 => array('id' => 288, 'alpha2' => 'gh', 'alpha3' => 'gha', 'name' => 'Gana', 'ddi' => 233),
    268 => array('id' => 268, 'alpha2' => 'ge', 'alpha3' => 'geo', 'name' => 'Geórgia', 'ddi' => 995),
    239 => array('id' => 239, 'alpha2' => 'gs', 'alpha3' => 'sgs', 'name' => 'Ilhas Geórgia do Sul e Sandwich do Sul', 'ddi' => 500),
    292 => array('id' => 292, 'alpha2' => 'gi', 'alpha3' => 'gib', 'name' => 'Gibraltar', 'ddi' => 350),
    308 => array('id' => 308, 'alpha2' => 'gd', 'alpha3' => 'grd', 'name' => 'Granada', 'ddi' => 1),
    300 => array('id' => 300, 'alpha2' => 'gr', 'alpha3' => 'grc', 'name' => 'Grécia', 'ddi' => 30),
    304 => array('id' => 304, 'alpha2' => 'gl', 'alpha3' => 'grl', 'name' => 'Gronelândia', 'ddi' => 299),
    312 => array('id' => 312, 'alpha2' => 'gp', 'alpha3' => 'glp', 'name' => 'Guadalupe', 'ddi' => 590),
    316 => array('id' => 316, 'alpha2' => 'gu', 'alpha3' => 'gum', 'name' => 'Guam', 'ddi' => 671),
    320 => array('id' => 320, 'alpha2' => 'gt', 'alpha3' => 'gtm', 'name' => 'Guatemala', 'ddi' => 502),
    831 => array('id' => 831, 'alpha2' => 'gg', 'alpha3' => 'ggy', 'name' => 'Guernsey', 'ddi' => 1),
    328 => array('id' => 328, 'alpha2' => 'gy', 'alpha3' => 'guy', 'name' => 'Guiana', 'ddi' => 592),
    254 => array('id' => 254, 'alpha2' => 'gf', 'alpha3' => 'guf', 'name' => 'Guiana Francesa', 'ddi' => 594),
    624 => array('id' => 624, 'alpha2' => 'gw', 'alpha3' => 'gnb', 'name' => 'Guiné-Bissau', 'ddi' => 245),
    324 => array('id' => 324, 'alpha2' => 'gn', 'alpha3' => 'gin', 'name' => 'Guiné', 'ddi' => 224),
    226 => array('id' => 226, 'alpha2' => 'gq', 'alpha3' => 'gnq', 'name' => 'Guiné Equatorial', 'ddi' => 240),
    332 => array('id' => 332, 'alpha2' => 'ht', 'alpha3' => 'hti', 'name' => 'Haiti', 'ddi' => 509),
    334 => array('id' => 334, 'alpha2' => 'hm', 'alpha3' => 'hmd', 'name' => 'Ilha Heard e Ilhas McDonald', 'ddi' => 672),
    340 => array('id' => 340, 'alpha2' => 'hn', 'alpha3' => 'hnd', 'name' => 'Honduras', 'ddi' => 504),
    344 => array('id' => 344, 'alpha2' => 'hk', 'alpha3' => 'hkg', 'name' => 'Hong Kong', 'ddi' => 852),
    348 => array('id' => 348, 'alpha2' => 'hu', 'alpha3' => 'hun', 'name' => 'Hungria', 'ddi' => 36),
    887 => array('id' => 887, 'alpha2' => 'ye', 'alpha3' => 'yem', 'name' => 'Iêmen', 'ddi' => 967),
    356 => array('id' => 356, 'alpha2' => 'in', 'alpha3' => 'ind', 'name' => 'Índia', 'ddi' => 91),
    360 => array('id' => 360, 'alpha2' => 'id', 'alpha3' => 'idn', 'name' => 'Indonésia', 'ddi' => 62),
    368 => array('id' => 368, 'alpha2' => 'iq', 'alpha3' => 'irq', 'name' => 'Iraque', 'ddi' => 964),
    364 => array('id' => 364, 'alpha2' => 'ir', 'alpha3' => 'irn', 'name' => 'Irã', 'ddi' => 98),
    372 => array('id' => 372, 'alpha2' => 'ie', 'alpha3' => 'irl', 'name' => 'Irlanda', 'ddi' => 353),
    352 => array('id' => 352, 'alpha2' => 'is', 'alpha3' => 'isl', 'name' => 'Islândia', 'ddi' => 354),
    376 => array('id' => 376, 'alpha2' => 'il', 'alpha3' => 'isr', 'name' => 'Israel', 'ddi' => 972),
    380 => array('id' => 380, 'alpha2' => 'it', 'alpha3' => 'ita', 'name' => 'Itália', 'ddi' => 39),
    388 => array('id' => 388, 'alpha2' => 'jm', 'alpha3' => 'jam', 'name' => 'Jamaica', 'ddi' => 1),
    392 => array('id' => 392, 'alpha2' => 'jp', 'alpha3' => 'jpn', 'name' => 'Japão', 'ddi' => 81),
    832 => array('id' => 832, 'alpha2' => 'je', 'alpha3' => 'jey', 'name' => 'Jersey', 'ddi' => 1),
    400 => array('id' => 400, 'alpha2' => 'jo', 'alpha3' => 'jor', 'name' => 'Jordânia', 'ddi' => 962),
    414 => array('id' => 414, 'alpha2' => 'kw', 'alpha3' => 'kwt', 'name' => 'Kuwait', 'ddi' => 965),
    418 => array('id' => 418, 'alpha2' => 'la', 'alpha3' => 'lao', 'name' => 'Laos', 'ddi' => 856),
    426 => array('id' => 426, 'alpha2' => 'ls', 'alpha3' => 'lso', 'name' => 'Lesoto', 'ddi' => 266),
    428 => array('id' => 428, 'alpha2' => 'lv', 'alpha3' => 'lva', 'name' => 'Letônia', 'ddi' => 371),
    422 => array('id' => 422, 'alpha2' => 'lb', 'alpha3' => 'lbn', 'name' => 'Líbano', 'ddi' => 961),
    430 => array('id' => 430, 'alpha2' => 'lr', 'alpha3' => 'lbr', 'name' => 'Libéria', 'ddi' => 231),
    434 => array('id' => 434, 'alpha2' => 'ly', 'alpha3' => 'lby', 'name' => 'Líbia', 'ddi' => 218),
    438 => array('id' => 438, 'alpha2' => 'li', 'alpha3' => 'lie', 'name' => 'Listenstaine', 'ddi' => 423),
    440 => array('id' => 440, 'alpha2' => 'lt', 'alpha3' => 'ltu', 'name' => 'Lituânia', 'ddi' => 370),
    442 => array('id' => 442, 'alpha2' => 'lu', 'alpha3' => 'lux', 'name' => 'Luxemburgo', 'ddi' => 352),
    446 => array('id' => 446, 'alpha2' => 'mo', 'alpha3' => 'mac', 'name' => 'Macau', 'ddi' => 853),
    807 => array('id' => 807, 'alpha2' => 'mk', 'alpha3' => 'mkd', 'name' => 'Macedônia do Norte', 'ddi' => 389),
    450 => array('id' => 450, 'alpha2' => 'mg', 'alpha3' => 'mdg', 'name' => 'Madagáscar', 'ddi' => 261),
    175 => array('id' => 175, 'alpha2' => 'yt', 'alpha3' => 'myt', 'name' => 'Maiote', 'ddi' => 262),
    458 => array('id' => 458, 'alpha2' => 'my', 'alpha3' => 'mys', 'name' => 'Malásia', 'ddi' => 60),
    454 => array('id' => 454, 'alpha2' => 'mw', 'alpha3' => 'mwi', 'name' => 'Maláui', 'ddi' => 265),
    462 => array('id' => 462, 'alpha2' => 'mv', 'alpha3' => 'mdv', 'name' => 'Maldivas', 'ddi' => 960),
    466 => array('id' => 466, 'alpha2' => 'ml', 'alpha3' => 'mli', 'name' => 'Mali', 'ddi' => 223),
    470 => array('id' => 470, 'alpha2' => 'mt', 'alpha3' => 'mlt', 'name' => 'Malta', 'ddi' => 356),
    238 => array('id' => 238, 'alpha2' => 'fk', 'alpha3' => 'flk', 'name' => 'Ilhas Malvinas', 'ddi' => 500),
    833 => array('id' => 833, 'alpha2' => 'im', 'alpha3' => 'imn', 'name' => 'Ilha de Man', 'ddi' => 44),
    580 => array('id' => 580, 'alpha2' => 'mp', 'alpha3' => 'mnp', 'name' => 'Marianas Setentrionais', 'ddi' => 1),
    504 => array('id' => 504, 'alpha2' => 'ma', 'alpha3' => 'mar', 'name' => 'Marrocos', 'ddi' => 212),
    584 => array('id' => 584, 'alpha2' => 'mh', 'alpha3' => 'mhl', 'name' => 'Ilhas Marshall', 'ddi' => 692),
    474 => array('id' => 474, 'alpha2' => 'mq', 'alpha3' => 'mtq', 'name' => 'Martinica', 'ddi' => 596),
    480 => array('id' => 480, 'alpha2' => 'mu', 'alpha3' => 'mus', 'name' => 'Ilhas Maurícias', 'ddi' => 230),
    478 => array('id' => 478, 'alpha2' => 'mr', 'alpha3' => 'mrt', 'name' => 'Mauritânia', 'ddi' => 222),
    581 => array('id' => 581, 'alpha2' => 'um', 'alpha3' => 'umi', 'name' => 'Ilhas Menores Distantes dos Estados Unidos', 'ddi' => 1),
    484 => array('id' => 484, 'alpha2' => 'mx', 'alpha3' => 'mex', 'name' => 'México', 'ddi' => 52),
    104 => array('id' => 104, 'alpha2' => 'mm', 'alpha3' => 'mmr', 'name' => 'Mianmar', 'ddi' => 95),
    583 => array('id' => 583, 'alpha2' => 'fm', 'alpha3' => 'fsm', 'name' => 'Estados Federados da Micronésia', 'ddi' => 691),
    508 => array('id' => 508, 'alpha2' => 'mz', 'alpha3' => 'moz', 'name' => 'Moçambique', 'ddi' => 258),
    498 => array('id' => 498, 'alpha2' => 'md', 'alpha3' => 'mda', 'name' => 'Moldávia', 'ddi' => 373),
    492 => array('id' => 492, 'alpha2' => 'mc', 'alpha3' => 'mco', 'name' => 'Mónaco', 'ddi' => 377),
    496 => array('id' => 496, 'alpha2' => 'mn', 'alpha3' => 'mng', 'name' => 'Mongólia', 'ddi' => 976),
    500 => array('id' => 500, 'alpha2' => 'ms', 'alpha3' => 'msr', 'name' => 'Monserrate', 'ddi' => 1),
    499 => array('id' => 499, 'alpha2' => 'me', 'alpha3' => 'mne', 'name' => 'Montenegro', 'ddi' => 382),
    516 => array('id' => 516, 'alpha2' => 'na', 'alpha3' => 'nam', 'name' => 'Namíbia', 'ddi' => 264),
    162 => array('id' => 162, 'alpha2' => 'cx', 'alpha3' => 'cxr', 'name' => 'Ilha do Natal', 'ddi' => 61),
    520 => array('id' => 520, 'alpha2' => 'nr', 'alpha3' => 'nru', 'name' => 'Nauru', 'ddi' => 674),
    524 => array('id' => 524, 'alpha2' => 'np', 'alpha3' => 'npl', 'name' => 'Nepal', 'ddi' => 977),
    558 => array('id' => 558, 'alpha2' => 'ni', 'alpha3' => 'nic', 'name' => 'Nicarágua', 'ddi' => 505),
    562 => array('id' => 562, 'alpha2' => 'ne', 'alpha3' => 'ner', 'name' => 'Níger', 'ddi' => 227),
    566 => array('id' => 566, 'alpha2' => 'ng', 'alpha3' => 'nga', 'name' => 'Nigéria', 'ddi' => 234),
    570 => array('id' => 570, 'alpha2' => 'nu', 'alpha3' => 'niu', 'name' => 'Niue', 'ddi' => 683),
    574 => array('id' => 574, 'alpha2' => 'nf', 'alpha3' => 'nfk', 'name' => 'Ilha Norfolk', 'ddi' => 672),
    578 => array('id' => 578, 'alpha2' => 'no', 'alpha3' => 'nor', 'name' => 'Noruega', 'ddi' => 47),
    540 => array('id' => 540, 'alpha2' => 'nc', 'alpha3' => 'ncl', 'name' => 'Nova Caledónia', 'ddi' => 687),
    554 => array('id' => 554, 'alpha2' => 'nz', 'alpha3' => 'nzl', 'name' => 'Nova Zelândia', 'ddi' => 64),
    512 => array('id' => 512, 'alpha2' => 'om', 'alpha3' => 'omn', 'name' => 'Omã', 'ddi' => 968),
    528 => array('id' => 528, 'alpha2' => 'nl', 'alpha3' => 'nld', 'name' => 'Países Baixos', 'ddi' => 31),
    585 => array('id' => 585, 'alpha2' => 'pw', 'alpha3' => 'plw', 'name' => 'Palau', 'ddi' => 680),
    275 => array('id' => 275, 'alpha2' => 'ps', 'alpha3' => 'pse', 'name' => 'Palestina', 'ddi' => 970),
    591 => array('id' => 591, 'alpha2' => 'pa', 'alpha3' => 'pan', 'name' => 'Panamá', 'ddi' => 507),
    598 => array('id' => 598, 'alpha2' => 'pg', 'alpha3' => 'png', 'name' => 'Papua-Nova Guiné', 'ddi' => 675),
    586 => array('id' => 586, 'alpha2' => 'pk', 'alpha3' => 'pak', 'name' => 'Paquistão', 'ddi' => 92),
    600 => array('id' => 600, 'alpha2' => 'py', 'alpha3' => 'pry', 'name' => 'Paraguai', 'ddi' => 595),
    604 => array('id' => 604, 'alpha2' => 'pe', 'alpha3' => 'per', 'name' => 'Peru', 'ddi' => 51),
    612 => array('id' => 612, 'alpha2' => 'pn', 'alpha3' => 'pcn', 'name' => 'Pitcairn', 'ddi' => 64),
    258 => array('id' => 258, 'alpha2' => 'pf', 'alpha3' => 'pyf', 'name' => 'Polinésia Francesa', 'ddi' => 689),
    616 => array('id' => 616, 'alpha2' => 'pl', 'alpha3' => 'pol', 'name' => 'Polónia', 'ddi' => 48),
    630 => array('id' => 630, 'alpha2' => 'pr', 'alpha3' => 'pri', 'name' => 'Porto Rico', 'ddi' => 1),
    620 => array('id' => 620, 'alpha2' => 'pt', 'alpha3' => 'prt', 'name' => 'Portugal', 'ddi' => 351),
    404 => array('id' => 404, 'alpha2' => 'ke', 'alpha3' => 'ken', 'name' => 'Quênia', 'ddi' => 254),
    417 => array('id' => 417, 'alpha2' => 'kg', 'alpha3' => 'kgz', 'name' => 'Quirguistão', 'ddi' => 996),
    296 => array('id' => 296, 'alpha2' => 'ki', 'alpha3' => 'kir', 'name' => 'Quiribáti', 'ddi' => 686),
    826 => array('id' => 826, 'alpha2' => 'gb', 'alpha3' => 'gbr', 'name' => 'Reino Unido', 'ddi' => 44),
    638 => array('id' => 638, 'alpha2' => 're', 'alpha3' => 'reu', 'name' => 'Reunião', 'ddi' => 262),
    642 => array('id' => 642, 'alpha2' => 'ro', 'alpha3' => 'rou', 'name' => 'Roménia', 'ddi' => 40),
    646 => array('id' => 646, 'alpha2' => 'rw', 'alpha3' => 'rwa', 'name' => 'Ruanda', 'ddi' => 250),
    643 => array('id' => 643, 'alpha2' => 'ru', 'alpha3' => 'rus', 'name' => 'Rússia', 'ddi' => 7),
    732 => array('id' => 732, 'alpha2' => 'eh', 'alpha3' => 'esh', 'name' => 'Saara Ocidental', 'ddi' => 212),
    16  => array('id' => 16 , 'alpha2' => 'as', 'alpha3' => 'asm', 'name' => 'Samoa Americana', 'ddi' => 1),
    882 => array('id' => 882, 'alpha2' => 'ws', 'alpha3' => 'wsm', 'name' => 'Samoa', 'ddi' => 685),
    90  => array('id' => 90 , 'alpha2' => 'sb', 'alpha3' => 'slb', 'name' => 'Ilhas Salomão', 'ddi' => 677),
    674 => array('id' => 674, 'alpha2' => 'sm', 'alpha3' => 'smr', 'name' => 'San Marino', 'ddi' => 378),
    654 => array('id' => 654, 'alpha2' => 'sh', 'alpha3' => 'shn', 'name' => 'Santa Helena, Ascensão e Tristão da Cunha', 'ddi' => 290),
    662 => array('id' => 662, 'alpha2' => 'lc', 'alpha3' => 'lca', 'name' => 'Santa Lúcia', 'ddi' => 1),
    652 => array('id' => 652, 'alpha2' => 'bl', 'alpha3' => 'blm', 'name' => 'São Bartolomeu', 'ddi' => 590),
    659 => array('id' => 659, 'alpha2' => 'kn', 'alpha3' => 'kna', 'name' => 'São Cristóvão e Neves', 'ddi' => 1),
    663 => array('id' => 663, 'alpha2' => 'mf', 'alpha3' => 'maf', 'name' => 'São Martinho', 'ddi' => 378),
    534 => array('id' => 534, 'alpha2' => 'sx', 'alpha3' => 'sxm', 'name' => 'São Martinho', 'ddi' => 378),
    666 => array('id' => 666, 'alpha2' => 'pm', 'alpha3' => 'spm', 'name' => 'São Pedro e Miquelão', 'ddi' => 508),
    678 => array('id' => 678, 'alpha2' => 'st', 'alpha3' => 'stp', 'name' => 'São Tomé e Príncipe', 'ddi' => 239),
    670 => array('id' => 670, 'alpha2' => 'vc', 'alpha3' => 'vct', 'name' => 'São Vicente e Granadinas', 'ddi' => 1),
    690 => array('id' => 690, 'alpha2' => 'sc', 'alpha3' => 'syc', 'name' => 'Seicheles', 'ddi' => 248),
    686 => array('id' => 686, 'alpha2' => 'sn', 'alpha3' => 'sen', 'name' => 'Senegal', 'ddi' => 221),
    144 => array('id' => 144, 'alpha2' => 'lk', 'alpha3' => 'lka', 'name' => 'Seri Lanca', 'ddi' => 94),
    694 => array('id' => 694, 'alpha2' => 'sl', 'alpha3' => 'sle', 'name' => 'Serra Leoa', 'ddi' => 232),
    688 => array('id' => 688, 'alpha2' => 'rs', 'alpha3' => 'srb', 'name' => 'Sérvia', 'ddi' => 381),
    702 => array('id' => 702, 'alpha2' => 'sg', 'alpha3' => 'sgp', 'name' => 'Singapura', 'ddi' => 65),
    760 => array('id' => 760, 'alpha2' => 'sy', 'alpha3' => 'syr', 'name' => 'Síria', 'ddi' => 963),
    706 => array('id' => 706, 'alpha2' => 'so', 'alpha3' => 'som', 'name' => 'Somália', 'ddi' => 252),
    729 => array('id' => 729, 'alpha2' => 'sd', 'alpha3' => 'sdn', 'name' => 'Sudão', 'ddi' => 249),
    728 => array('id' => 728, 'alpha2' => 'ss', 'alpha3' => 'ssd', 'name' => 'Sudão do Sul', 'ddi' => 211),
    752 => array('id' => 752, 'alpha2' => 'se', 'alpha3' => 'swe', 'name' => 'Suécia', 'ddi' => 46),
    756 => array('id' => 756, 'alpha2' => 'ch', 'alpha3' => 'che', 'name' => 'Suíça', 'ddi' => 41),
    740 => array('id' => 740, 'alpha2' => 'sr', 'alpha3' => 'sur', 'name' => 'Suriname', 'ddi' => 597),
    764 => array('id' => 764, 'alpha2' => 'th', 'alpha3' => 'tha', 'name' => 'Tailândia', 'ddi' => 66),
    158 => array('id' => 158, 'alpha2' => 'tw', 'alpha3' => 'twn', 'name' => 'Taiwan', 'ddi' => 886),
    762 => array('id' => 762, 'alpha2' => 'tj', 'alpha3' => 'tjk', 'name' => 'Tajiquistão', 'ddi' => 992),
    834 => array('id' => 834, 'alpha2' => 'tz', 'alpha3' => 'tza', 'name' => 'Tanzânia', 'ddi' => 255),
    86  => array('id' => 86 , 'alpha2' => 'io', 'alpha3' => 'iot', 'name' => 'Território Britânico do Oceano Índico', 'ddi' => 246),
    626 => array('id' => 626, 'alpha2' => 'tl', 'alpha3' => 'tls', 'name' => 'Timor-Leste', 'ddi' => 670),
    768 => array('id' => 768, 'alpha2' => 'tg', 'alpha3' => 'tgo', 'name' => 'Togo', 'ddi' => 228),
    776 => array('id' => 776, 'alpha2' => 'to', 'alpha3' => 'ton', 'name' => 'Tonga', 'ddi' => 676),
    772 => array('id' => 772, 'alpha2' => 'tk', 'alpha3' => 'tkl', 'name' => 'Toquelau', 'ddi' => 690),
    780 => array('id' => 780, 'alpha2' => 'tt', 'alpha3' => 'tto', 'name' => 'Trinidad e Tobago', 'ddi' => 1),
    788 => array('id' => 788, 'alpha2' => 'tn', 'alpha3' => 'tun', 'name' => 'Tunísia', 'ddi' => 216),
    796 => array('id' => 796, 'alpha2' => 'tc', 'alpha3' => 'tca', 'name' => 'Turcas e Caicos', 'ddi' => 1),
    795 => array('id' => 795, 'alpha2' => 'tm', 'alpha3' => 'tkm', 'name' => 'Turcomenistão', 'ddi' => 993),
    792 => array('id' => 792, 'alpha2' => 'tr', 'alpha3' => 'tur', 'name' => 'Turquia', 'ddi' => 90),
    798 => array('id' => 798, 'alpha2' => 'tv', 'alpha3' => 'tuv', 'name' => 'Tuvalu', 'ddi' => 688),
    804 => array('id' => 804, 'alpha2' => 'ua', 'alpha3' => 'ukr', 'name' => 'Ucrânia', 'ddi' => 380),
    800 => array('id' => 800, 'alpha2' => 'ug', 'alpha3' => 'uga', 'name' => 'Uganda', 'ddi' => 256),
    858 => array('id' => 858, 'alpha2' => 'uy', 'alpha3' => 'ury', 'name' => 'Uruguai', 'ddi' => 598),
    860 => array('id' => 860, 'alpha2' => 'uz', 'alpha3' => 'uzb', 'name' => 'Uzbequistão', 'ddi' => 998),
    548 => array('id' => 548, 'alpha2' => 'vu', 'alpha3' => 'vut', 'name' => 'Vanuatu', 'ddi' => 678),
    336 => array('id' => 336, 'alpha2' => 'va', 'alpha3' => 'vat', 'name' => 'Vaticano', 'ddi' => 379),
    862 => array('id' => 862, 'alpha2' => 've', 'alpha3' => 'ven', 'name' => 'Venezuela', 'ddi' => 58),
    704 => array('id' => 704, 'alpha2' => 'vn', 'alpha3' => 'vnm', 'name' => 'Vietname', 'ddi' => 84),
    850 => array('id' => 850, 'alpha2' => 'vi', 'alpha3' => 'vir', 'name' => 'Ilhas Virgens Americanas', 'ddi' => 1),
    92  => array('id' => 92 , 'alpha2' => 'vg', 'alpha3' => 'vgb', 'name' => 'Ilhas Virgens Britânicas', 'ddi' => 1),
    876 => array('id' => 876, 'alpha2' => 'wf', 'alpha3' => 'wlf', 'name' => 'Wallis e Futuna', 'ddi' => 681),
    894 => array('id' => 894, 'alpha2' => 'zm', 'alpha3' => 'zmb', 'name' => 'Zâmbia', 'ddi' => 260),
    716 => array('id' => 716, 'alpha2' => 'zw', 'alpha3' => 'zwe', 'name' => 'Zimbábue', 'ddi' => 263)
);